### ISSUE TITLE
Suggestion for Tower Effect

### ISSUE THREAD

**Issue by ChapperNi** [Asonyx/LCTarrotCard#1]
Right now, one of the effects of the tower is arguably worse than that of Death because it spells an instant game over for whoever isnt on the ship (pulling the ships lever), or a quota loss if nobody is on the ship. I know its a 1/5 chance because it selects an effect from the list, but this doesnt help much because the tower is one of the most common effects with Wheel of Fortune. Could you adjust the effect on it, please?

**Comment by Asonyx** [comment]
Hello, I had people telling me the same thing, it is going to change next update (what I think will happen is you being able to decide the probability of this effect). But for now the card is not 1/5 chance, but 1/60 because not every effect has the same chance if happening (it is not specified in the readme but it is the case)
